### ISSUE TITLE
suggestions on README

### ISSUE THREAD

**Issue by paciorek** [berkeley-scf/stat999-myst#4]
- [x] Move "instructions for course staff" above "instructions for department staff". 
- [x] I like the mermaid diagram, but I think it buries the lede in a way :)  -- namely it doesn't make clear what the non-advanced way is to modify the repo - I guess this would be an arrow somehow indicating direct changes to g.com/berkeley-stat555/spring-2024. I'm not actually sure we need/want the advanced approach in the diagram...
- [x] Why "theoretically" in "theoretically the instructor could ask the SCF". I thought we imagined this would be the main approach - bootstrapping each semester off the previous semester.
- [x] I changed in one place, but just a note that `github.com/berkeley-stat555/spring-2024` is what exists (not `fall-2024`), so perhaps change to `fall-2024` throughout?
- [ ] #5

**Comment by ryanlovett** [comment]
I've made a few fixes for 1, 3, and 4.

Regarding 2, the advanced steps do take up more space on the diagram than the simpler process of just making direct commits. I'll try to emphasize the latter. Alternatively I wonder if it makes sense to have a regular workflow diagram and a separate one for the advanced.

Regarding 5, for groups to do shared development but keep it private, I think they'd need a private repo. I doubt this comes with GitHub Pages support however since that would be public. Perhaps this should be a separate issue.

**Comment by ryanlovett** [comment]
I split the workflow in two which hopefully addresses your 2nd point.

I'll close this issue in favor of #5.
